### ISSUE TITLE
About the calculation of robust acc under black-box attacks

### ISSUE THREAD

**Issue by momo1986** [SCLBD/BlackboxBench#1]
Hi, I thank you for your contributions in robustness study. When I run the black-box attacks, if the total failure rate is 0.8, clean acc is 0.9, what is the robust acc under black-box attacks?
1. Misclassified samples in normal testing is thrown. Then robust acc is 0.9*0.8=0.72.
2. All samples are tested, thus, robust acc is 0.8.
I am not sure which one is correct?
Could the dear colleagues from BlackBoxBench team help me?
Thanks!
I wish you are all good!
Momo

**Comment by Alan-Qin** [comment]
Thanks for your question.

Actually, we just test the correctly classified samples when conducting the attack.  Therefore, the final robust acc is failure attacks over correctly classified samples. So, the final robust acc is just the total failure rate.

Thanks!
