### ISSUE TITLE
The New Version

### ISSUE THREAD

**Issue by RoeyBokobza** [SCLBD/BlackboxBench#10]
Hey, 

I have been using this library for quite a while for my research ( this is the time to mention that I had a great experience doing so).
I noticed that you have changed the library completely in your last update. There are no attacks implementations, and basically all query-based attacks files are no longer available, thus cannot be performed and used.  

I would love to get some help, since my research is based on the ability to run those attacks. 

Thank you.

**Comment by zhengmeixi** [comment]
Hi,
Thanks for using BlackboxBench. We did update it to version 2 recently. This new version contains both transfer and query-based attacks. Sorry for not clarifying this in README clearly, we will complete it later.
For your questions:
(1) There are no attacks implementations
The Quick Start part is moving to the README.md file under `transfer`/`query `folder.
(2) all query-based attacks files are no longer available
You can still find the original version in v1 branch, or you can find them in `query` folder (same as the v1 branch).

Please let me know if you have any further questions and I will be happy to assist you!! :)
